# Evaluating the model 

## Loading Model

In [1]:
import tensorflow as tf
from tensorflow import keras
from keras.models import load_model
from keras.metrics import Precision, Recall, Accuracy, F1Score
from keras.utils import image_dataset_from_directory, load_img

c:\Users\foxin\AppData\Local\Programs\Python\Python310\lib\site-packages\numpy\_distributor_init.py:30: UserWarning: loaded more than 1 DLL from .libs:
c:\Users\foxin\AppData\Local\Programs\Python\Python310\lib\site-packages\numpy\.libs\libopenblas.XWYDX2IKJW2NMTWSFYNGFUWKQU3LYTCZ.gfortran-win_amd64.dll
c:\Users\foxin\AppData\Local\Programs\Python\Python310\lib\site-packages\numpy\.libs\libopenblas64__v0.3.21-gcc_10_3_0.dll
c:\Users\foxin\AppData\Local\Programs\Python\Python310\lib\site-packages\numpy\.libs\libopenblas64__v0.3.23-gcc_10_3_0.dll
  warnings.warn("loaded more than 1 DLL from .libs:"


In [2]:
model = load_model('model.h5')

In [3]:
model.summary()

Model: "sequential_1"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 conv2d_3 (Conv2D)           (None, 254, 254, 16)      448       
                                                                 
 max_pooling2d_3 (MaxPoolin  (None, 127, 127, 16)      0         
 g2D)                                                            
                                                                 
 dropout_4 (Dropout)         (None, 127, 127, 16)      0         
                                                                 
 conv2d_4 (Conv2D)           (None, 125, 125, 32)      4640      
                                                                 
 max_pooling2d_4 (MaxPoolin  (None, 62, 62, 32)        0         
 g2D)                                                            
                                                                 
 dropout_5 (Dropout)         (None, 62, 62, 32)       

## Predicting images

In [24]:
def predict(image:str):
    """
    Predicts if an image is suv or supercar
    Takes in image path as an argument
    """
    img = tf.expand_dims(tf.convert_to_tensor(load_img(image).resize((256, 256))), 0)
    labels = ['supercars', 'suv']

    return labels[int(model.predict(img, verbose=False)[0])]


In [26]:
predict('unprocessed data/supercars/19-DEC-2016-THE-LAMBORGHINI-AVENTADOR-S-TA.jpg')

'supercars'

The model seems to be working properly

## Evaluating The Scores

In [46]:
testData = image_dataset_from_directory('data/test')

Found 1051 files belonging to 2 classes.


In [47]:
pre = Precision()
re = Recall()

In [48]:
for batch in testData:
    x, y = batch
    yhat = tf.cast(model.predict(x), tf.float32)

    pre.update_state(y, yhat)
    re.update_state(y, yhat)

1/1 [==============================] - 1s 1s/step


In [50]:
f1 = 2 * (re.result() * pre.result()) / (re.result() + pre.result())

In [53]:
print(f"[BenchMarks] Precision: {tf.round(pre.result()*100)}%\tRecall: {tf.round(re.result()*100)}%\tF1: {tf.round(f1*100)}%")

[BenchMarks] Precision: 94.0%	Recall: 95.0%	F1: 94.0%


The model is performing good with [BenchMarks] Precision: 94.0%	Recall: 95.0%	F1: 94.0%